### ISSUE TITLE
LOGO

### ISSUE THREAD

**Issue by ghost** [abertschi/ad-free#23]

**Comment by jackneilson1** [comment]
Sorry, I am not interested.


On 15 May 2018 at 10:41, <waqasanwar94 <notifications@github.com>> wrote:

Hello, @abertschi <https://github.com/abertschi> I want to contribute in
"ad-free" so i want to design a new logo for "ad-free" and it's free.

I hope you like it. If you like it, I will send you to pull request,
editable files/original source and .png format files. If there's something
you want to change, I'll do it.

if you want i will send you my design

Contact me on facebook for fast delivery
https://www.facebook.com/waqasanwar68

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/abertschi/ad-free/issues/23>, or mute the thread
