### ISSUE TITLE
Mute adds for Spotify Lite 

### ISSUE THREAD

**Issue by yersontry** [abertschi/ad-free#26]
The app works fine with Spotify full version but doesn't support Spotify Lite

**Comment by abertschi** [comment]
ad-free is currently not compatible with the lite version. There is nothing in the notification bundle that can be exploited. The only possible implementation I can think of is manual tagging of ads. So whenever an ad appears, one has to mark it as unwanted in order to allow ad-free to block it when it appears again. Given the fact that the lite version is still beta, I am not planning to implement manual tagging in the close future.
