### ISSUE TITLE
No Ads Blocked

### ISSUE THREAD

**Issue by nomr72** [abertschi/ad-free#46]
I'm on an A501DL running Android 8.1.0 and I have no indication the app is doing anything, even on logcat.  Spotify plays all the ads, showing a distinctive notification for them too.  I tried the music note button in the app, and it will silence the playback when I ask, it just doesn't do it on its own.

**Comment by abertschi** [comment]
seems like an issue with the notification listener. Did you properly enable it? You can try to disable and enable it in the system settings app ("notification access"). Another thing to try is to remove ad-free among the list of battery saved apps so that services aren't killed ("battery optimization"). Can you post the logcat output?

**Comment by abertschi** [comment]
fixed in version #52
