### ISSUE TITLE
Muting issue

### ISSUE THREAD

**Issue by andras-szuecs** [abertschi/ad-free#72]
The app recognises when ads play(notification pops up), but doesn't mute them. I'm running on Android 10 on an Oppo device.

**Comment by andras-szuecs** [comment]
Do you have any tips? Where should i start?

**Comment by abertschi** [comment]
Has it ever worked on this device on previous versions of either OS, spotify or adfree?

In any case, you can debug why the mute of stream music does not mute playback. The issue seems device specific.

See here as a start:
https://github.com/abertschi/ad-free/blob/master/app/src/main/java/ch/abertschi/adfree/AudioController.kt
